### ISSUE TITLE
Unstable Version Detected

### ISSUE THREAD

**Issue by fabionegro-it** [erickok/app_set_id#3]
Hi! I would like to use the app_set_id plugin in my Flutter application. My CI/CD procedure checks for any vulnerable dependencies. For the app_set_id plugin, an unstable version is detected due to the version indicated in the build.gradle file of the native Android component (1.0-SNAPSHOT). Is it possible to align the version in the build.gradle file with the same version as the Dart plugin?

**Comment by erickok** [comment]
This was release as 1.2.1. Thanks for the feedback.
