### ISSUE TITLE
Getting build error on android with `1.2.1`

### ISSUE THREAD

**Issue by mark8044** [erickok/app_set_id#4]
Im getting the following build error only on android, iOS is fine

```
/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:24: error: cannot find symbol
      flutterEngine.getPlugins().add(new nl.u2312.app_set_id.AppSetIdPlugin());
                                                            ^
  symbol:   class AppSetIdPlugin
  location: package nl.u2312.app_set_id
1 error

FAILURE: Build failed with an exception.
```

This has started to occur today with upgrade to 1.2.1

BTW here is my flutter version:

```
Flutter 3.26.0-1.0.pre.390 • channel master • https://github.com/flutter/flutter.git
Framework • revision 42aa02f4e3 (59 minutes ago) • 2024-10-07 21:44:35 -0400
Engine • revision 07c702f2d7
Tools • Dart 3.6.0 (build 3.6.0-328.0.dev) • DevTools 2.40.0
```

Otherwise, the repo has been outstanding, love it and works really well with previous versions.
Much thanks

**Comment by erickok** [comment]
Thanks for the report. That's odd, I had no problem with this in de example app, but indeed I can reproduce it on my end. Sorry! Will try to fix this asap.

**Comment by erickok** [comment]
Can you try to do a `flutter clean` and a rebuild? It worked for me after a clean. If not, can you open your `GeneratedPluginRegistrant.java` and see if `AppSetIdPlugin` is in there?

**Comment by mark8044** [comment]
@erickok Ok so I did a `flutter pub upgrade` and it does look like the problem is solved now--- alls well that ends well.  I can leave this issue open if you think anything needs to be done otherwise it should be closed.

Thanks again

**Comment by erickok** [comment]
Good to hear. Yes I think that's all needed. Will close this ticket soon, to get a bit more visibility.
